# Generated by Django 6.0.5 on 2026-05-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationhistory',
            name='notify_type',
            field=models.CharField(choices=[('MAIL', 'Email'), ('PUSH', 'Push Notification'), ('INAPP', 'In-App Notification')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
    ]
