# Generated by Django 6.0.5 on 2026-05-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_alter_notificationhistory_notify_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('expertise', models.CharField(blank=True, max_length=255, null=True)),
                ('otp_code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='notify_type',
            field=models.CharField(default='MAIL', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='recipient_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
