# Generated by Django 6.0.5 on 2026-05-13 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0004_passwordresetotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
        migrations.DeleteModel(
            name='ProfessionalOTP',
        ),
    ]
