# Generated by Django 6.0.5 on 2026-05-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notify_type', models.CharField(default='MAIL', max_length=50)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email history',
                'verbose_name_plural': 'Email histories',
                'db_table': 'Elite_mail_emailhistory',
            },
        ),
    ]
