# Generated by Django 6.0.5 on 2026-05-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailhistory',
            old_name='recipient_name',
            new_name='user',
        ),
        migrations.AddField(
            model_name='emailhistory',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
