# Generated by Django 6.0.5 on 2026-05-15 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_mail', '0002_rename_recipient_name_emailhistory_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
            ],
            options={
                'verbose_name': 'Booking history',
                'verbose_name_plural': 'Booking histories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Elite_mail.emailhistory',),
        ),
    ]
