# Generated by Django 6.0.5 on 2026-05-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_mail', '0003_bookinghistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EliteInAppHistory',
            fields=[
            ],
            options={
                'verbose_name': 'Elite Inapp',
                'verbose_name_plural': 'Elite Inapp',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Elite_mail.emailhistory',),
        ),
        migrations.CreateModel(
            name='HireInAppHistory',
            fields=[
            ],
            options={
                'verbose_name': 'Hire Inapp',
                'verbose_name_plural': 'Hire Inapp',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Elite_mail.emailhistory',),
        ),
        migrations.CreateModel(
            name='HireMailHistory',
            fields=[
            ],
            options={
                'verbose_name': 'Hire Mail',
                'verbose_name_plural': 'Hire Mail',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Elite_mail.emailhistory',),
        ),
        migrations.AlterModelOptions(
            name='bookinghistory',
            options={'verbose_name': 'Booking history', 'verbose_name_plural': 'Booking history'},
        ),
        migrations.AlterModelOptions(
            name='emailhistory',
            options={'verbose_name': 'Email history', 'verbose_name_plural': 'Email history'},
        ),
        migrations.AddField(
            model_name='emailhistory',
            name='channel',
            field=models.CharField(default='EMAIL', max_length=50),
        ),
        migrations.AddField(
            model_name='emailhistory',
            name='project',
            field=models.CharField(default='ELITE', max_length=50),
        ),
    ]
