# Generated by Django 6.0.5 on 2026-05-15 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_mail', '0004_eliteinapphistory_hireinapphistory_hiremailhistory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HireInAppHistory',
        ),
        migrations.DeleteModel(
            name='HireMailHistory',
        ),
        migrations.CreateModel(
            name='EliteMailHistory',
            fields=[
            ],
            options={
                'verbose_name': 'Mail',
                'verbose_name_plural': 'Mail',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Elite_mail.emailhistory',),
        ),
        migrations.AlterModelOptions(
            name='bookinghistory',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Booking'},
        ),
        migrations.AlterModelOptions(
            name='eliteinapphistory',
            options={'verbose_name': 'Inapp', 'verbose_name_plural': 'Inapp'},
        ),
    ]
