# Generated by Django 6.0.5 on 2026-05-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('notify_type', models.CharField(default='MAIL', max_length=50)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('project', models.CharField(default='ELITE', max_length=50)),
                ('channel', models.CharField(default='EMAIL', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email history',
                'verbose_name_plural': 'Email history',
                'db_table': 'Elite_mail_emailhistory',
            },
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Booking',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Elite_freelancer.emailhistory',),
        ),
        migrations.CreateModel(
            name='EliteInAppHistory',
            fields=[
            ],
            options={
                'verbose_name': 'Inapp',
                'verbose_name_plural': 'Inapp',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Elite_freelancer.emailhistory',),
        ),
        migrations.CreateModel(
            name='EliteMailHistory',
            fields=[
            ],
            options={
                'verbose_name': 'Mail',
                'verbose_name_plural': 'Mail',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Elite_freelancer.emailhistory',),
        ),
    ]
