# Generated by Django 6.0.5 on 2026-05-15 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_freelancer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailhistory',
            table='elite_freelancer',
        ),
    ]
