# Generated by Django 6.0.5 on 2026-05-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_freelancer', '0002_alter_emailhistory_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField()),
                ('notify_type', models.CharField(default='MAIL', max_length=50)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('project', models.CharField(default='ELITE', max_length=50)),
                ('channel', models.CharField(default='EMAIL', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Booking',
                'db_table': 'elite_freelancer"."booking',
            },
        ),
        migrations.CreateModel(
            name='Inapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField()),
                ('notify_type', models.CharField(default='MAIL', max_length=50)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('project', models.CharField(default='ELITE', max_length=50)),
                ('channel', models.CharField(default='EMAIL', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inapp',
                'verbose_name_plural': 'Inapp',
                'db_table': 'elite_freelancer"."inapp',
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField()),
                ('notify_type', models.CharField(default='MAIL', max_length=50)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('project', models.CharField(default='ELITE', max_length=50)),
                ('channel', models.CharField(default='EMAIL', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mail',
                'verbose_name_plural': 'Mail',
                'db_table': 'elite_freelancer"."mail',
            },
        ),
        migrations.DeleteModel(
            name='EmailHistory',
        ),
        migrations.DeleteModel(
            name='BookingHistory',
        ),
        migrations.DeleteModel(
            name='EliteInAppHistory',
        ),
        migrations.DeleteModel(
            name='EliteMailHistory',
        ),
    ]
