# Generated by Django 6.0.5 on 2026-05-15 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_freelancer', '0003_booking_inapp_mail_delete_emailhistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='project',
        ),
        migrations.RemoveField(
            model_name='inapp',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='inapp',
            name='project',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='project',
        ),
    ]
