# Generated by Django 6.0.5 on 2026-05-15 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_freelancer', '0004_remove_booking_channel_remove_booking_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='notify_type',
        ),
        migrations.RemoveField(
            model_name='inapp',
            name='notify_type',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='notify_type',
        ),
    ]
