# Generated by Django 6.0.5 on 2026-05-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_freelancer', '0005_remove_booking_notify_type_remove_inapp_notify_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('token', models.TextField(unique=True)),
                ('platform', models.CharField(default='android', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Push token',
                'verbose_name_plural': 'Push tokens',
                'db_table': 'elite_freelancer"."push_token',
            },
        ),
    ]
